using System.ComponentModel.Composition;

namespace ProjectEuler
{
    [Export(typeof(IProblem))]
    internal class Problem2 : IProblem
    {
        public int Number => 2;
        public string Name => "Even Fibonacci numbers";

        public string Description => @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";

        public string Solve()
        {
            var sum = 0;
            var firstTerm = 1;
            var secondTerm = 2;
            while (secondTerm <= 4000000)
            {
                if (secondTerm % 2 == 0)
                {
                    sum += secondTerm;
                }

                var temp = secondTerm;
                secondTerm += firstTerm;
                firstTerm = temp;
            }

            return sum.ToString();
        }
    }
}
